"""The conversation, over HTTP, for a panel that is not a Gradio component.

The Forge Assistant is a DOM shell appended to ``document.body``, because there
is no supported Forge callback that mounts a Gradio component outside the tab
tree. So it cannot be given the conversation through Gradio's own transport,
and these routes are how it reads and writes instead.

Nothing here decides anything. Every route is a thin skin over
:mod:`mc_llm_conversation_service`, which is where validation, revisions,
deduplication and refusals live; a second copy of that reasoning behind an HTTP
handler is how the two views would come to disagree about what "delete message
4" means.

The capability
--------------
Exactly the pattern ``mc_voice_api`` already uses, and for the reason that
module's own docstring gives: the WebUI's login is what gets you the page, and
the page is where Python writes a per-process token into a hidden field. A
browser on another origin cannot read that field, cannot guess 24 random bytes,
and is refused by the same-origin check as well. There is no second sign-in
here because a second sign-in only ever produced a new way to be locked out.

The token travels in a header, never in a query string, and is never logged.
It is regenerated by a restart, which is what makes a tab left open across one
fail with "reload the page" rather than half-work.

Events
------
One feed per page, read as ``text/event-stream``. The reader in the browser is
``fetch``-based rather than ``EventSource`` for one reason: ``EventSource``
cannot send a header, and the capability has to travel in one.

Nothing here polls. The fallback to polling exists in the page for the case
where the stream cannot be held open at all -- a proxy that buffers, a network
that keeps dropping -- and it is transport of last resort, not a design.
"""

from __future__ import annotations

import json
import logging
import secrets
import threading
import time

import mc_llm_conversation_feed as feed
import mc_llm_conversation_service as service

logger = logging.getLogger("model_chain")
"""Handler is attached once, in mc_memory."""

try:                                                 # pragma: no cover - host only
    from fastapi import Request
    from fastapi.responses import JSONResponse, Response, StreamingResponse
except Exception:                                    # pragma: no cover - tests
    Request = None
    JSONResponse = Response = StreamingResponse = None

PREFIX = "/model-chain/conversation/v2"

BOOTSTRAP_ROUTE = f"{PREFIX}/bootstrap"
COMMANDS_ROUTE = f"{PREFIX}/commands"
SNAPSHOT_ROUTE = f"{PREFIX}/snapshot"
OPERATION_ROUTE = f"{PREFIX}/operations/{{operation_id}}"
RESOLVE_ROUTE = f"{PREFIX}/operations/{{operation_id}}/resolve"
SUBSCRIBE_ROUTE = f"{PREFIX}/subscribe"
EVENTS_ROUTE = f"{PREFIX}/events"
ATTACHMENTS_ROUTE = f"{PREFIX}/attachments"
ATTACHMENT_ROUTE = f"{PREFIX}/attachments/{{token}}"
WORKSPACES_ROUTE = f"{PREFIX}/workspaces"
SERVED_ROUTE = f"{PREFIX}/attachment/{{ticket}}"

ROUTES = (BOOTSTRAP_ROUTE, COMMANDS_ROUTE, SNAPSHOT_ROUTE, OPERATION_ROUTE, RESOLVE_ROUTE,
          SUBSCRIBE_ROUTE, EVENTS_ROUTE, ATTACHMENTS_ROUTE, ATTACHMENT_ROUTE,
          WORKSPACES_ROUTE, SERVED_ROUTE)

HEADER = "x-mc-conversation-key"
"""Where the capability travels. A header, so it is never in a URL.

A query string reaches the access log, the browser history and the ``Referer``
of everything the page loads afterwards. A header reaches the handler.
"""

MAX_BODY = 512 * 1024
"""The largest command body accepted. Half a mebibyte.

The text limit is 256 KiB and the rest is envelope, so this is twice what an
honest request can be and a long way short of what an unbounded read costs.
"""

MAX_UPLOAD = 24 * 1024 * 1024
"""The largest multipart upload read. A little above the staging limit.

Bounded here as well as in staging because this is the number that decides how
much is read into memory before anything has looked at it.
"""

STREAM_IDLE = 0.5
"""How long one feed read waits before the stream checks its client is there."""

HEARTBEAT = 15.0
"""How long an idle stream waits before writing a comment. Fifteen seconds.

Proxies close connections that say nothing. A comment line is two bytes and is
ignored by every SSE reader, which makes it the cheapest possible way to be
sure the silence is ours rather than the network's.
"""

_token = secrets.token_urlsafe(24)
"""This process's page token. Regenerated by a restart."""

_installed = False
_guard = threading.Lock()


def session_token() -> str:
    """The capability this process's pages are given. Never logged."""
    return _token


def reset_token() -> str:
    """Mint a new token, invalidating every page. For the tests."""
    global _token

    _token = secrets.token_urlsafe(24)
    return _token


# --------------------------------------------------------------------------- #
# Gates
# --------------------------------------------------------------------------- #


class Refused(Exception):
    def __init__(self, reason: str, status: int = 403):
        super().__init__(reason)
        self.reason = reason
        self.status = status


def _same_origin(request) -> bool:
    """Reject a page on another origin driving these routes with our cookies.

    Only when an ``Origin`` is present: a same-origin ``fetch`` from some
    browsers does not send one, and treating its absence as hostile would break
    the ordinary case to defend against a case the token already covers.
    ``X-Forwarded-Host`` is honoured because a reverse proxy is a documented
    deployment -- and it is compared rather than trusted blindly, which is the
    difference between supporting a proxy and having no check at all.
    """
    headers = getattr(request, "headers", {}) or {}
    origin = headers.get("origin")
    if not origin:
        return True
    wanted = {headers.get("host"), headers.get("x-forwarded-host")}
    wanted.discard(None)
    try:
        from urllib.parse import urlsplit

        netloc = urlsplit(origin).netloc
    except Exception:
        return False
    return bool(netloc) and netloc in wanted


def _matches(offered: str) -> bool:
    """Constant-time comparison that cannot be made to raise.

    ``compare_digest`` on ``str`` needs both sides ASCII and raises otherwise,
    so a header with one accented character would leave a route as a 500 rather
    than as the refusal it is.
    """
    import hmac

    try:
        return hmac.compare_digest(str(offered or "").encode("utf-8"),
                                   _token.encode("utf-8"))
    except Exception:                                # pragma: no cover - defensive
        return False


def checked(request) -> None:
    """Every gate one conversation route passes. Raises :class:`Refused`."""
    if not _same_origin(request):
        raise Refused("This request came from another page.", 403)
    headers = getattr(request, "headers", {}) or {}
    if not _matches(headers.get(HEADER)):
        raise Refused("Reload the page — this tab's key is from an earlier session.", 401)


# --------------------------------------------------------------------------- #
# Answers
# --------------------------------------------------------------------------- #


def _json(payload: dict, status: int = 200):
    return JSONResponse(payload, status_code=status)


def _refusal(exc: Refused):
    return _json({"ok": False, "error": {"code": service.AUTH_REQUIRED if exc.status == 401
                                         else service.FORBIDDEN,
                                         "message": exc.reason, "retryable": False}},
                 exc.status)


def _failed(what: str, message: str, status: int = 500):
    logger.warning("Model Chain: %s", what, exc_info=True)
    return _json({"ok": False, "error": {"code": service.SAVE_FAILED, "message": message,
                                         "retryable": status >= 500}}, status)


async def _body(request) -> dict:
    raw = await request.body()
    if len(raw) > MAX_BODY:
        raise Refused("That request is too large.", 413)
    try:
        found = json.loads(raw.decode("utf-8"))
    except (ValueError, UnicodeDecodeError):
        raise Refused("That request was not JSON.", 400)
    if not isinstance(found, dict):
        raise Refused("That request was not an object.", 400)
    return found


# --------------------------------------------------------------------------- #
# The handlers, as plain functions so they can be tested without a server
# --------------------------------------------------------------------------- #


def bootstrap(page_id: str = "") -> dict:
    return service.bootstrap(page_id)


def commands(body: dict) -> tuple[dict, int]:
    outcome = service.submit(body)
    status = int(outcome.pop("status", 200 if outcome.get("ok") else 400))
    return outcome, status


def snapshot(character: str, thread: str, selection_epoch: str = "",
             cursor: int | None = None) -> dict:
    return service.snapshot(character, thread, selection_epoch, cursor)


def operation(operation_id: str) -> tuple[dict, int]:
    """What happened to one operation. The answer to "did my message send?".

    A page whose response was lost asks this before doing anything else, and it
    is why it never has to guess: the record is here while the process lives,
    and the receipt is in the chat file afterwards. Neither answer is "probably
    not, try again", which is the answer that produces two messages.
    """
    import mc_llm_conversation_ops as ops

    found = ops.get(operation_id)
    if found is not None:
        return {"ok": True, "operation": found.describe(),
                "server_epoch": service.SERVER_EPOCH}, 200
    record = service.registry.find(service.DEFAULT_SCOPE, str(operation_id or ""))
    if record is not None:
        return {"ok": True, "operation": {"operation_id": record.operation_id,
                                          "phase": record.state},
                "outcome": record.outcome, "server_epoch": service.SERVER_EPOCH}, 200
    return {"ok": False, "error": {"code": service.NOT_FOUND,
                                   "message": "This server has no record of that request.",
                                   "retryable": False},
            "server_epoch": service.SERVER_EPOCH}, 404


def subscribe(page_id: str = "") -> dict:
    """Open a feed and take the snapshot cursor in the same breath.

    Both under the feed's lock, which is the race specification 8.4 names: an
    event that landed between reading the conversation and starting to listen
    would be delivered to nobody, and the page would sit one message behind
    until something else happened to arrive.
    """
    opened = feed.subscribe(page_id=page_id)
    return {"ok": True, "feed": opened.identifier,
            "subscription_generation": opened.generation,
            "stream_cursor": opened.cursor, "server_epoch": service.SERVER_EPOCH}


def workspaces() -> dict:
    """What the picker offers, as far as Python knows.

    Deliberately thin. The host's tab registry lives in the browser -- it *is*
    the DOM -- and the assistant reads it there; this route exists so that a
    page can be told which workspaces this extension owns and whether LLM
    Studio is even enabled, which is a Python fact.
    """
    import mc_llm_studio

    found = []
    try:
        if mc_llm_studio.enabled():
            found.append({"id": mc_llm_studio.TAB_ID, "label": mc_llm_studio.TAB_LABEL,
                          "modes": [{"value": value, "label": label}
                                    for label, value in mc_llm_studio.MODES]})
    except Exception:
        logger.debug("Model Chain: could not describe the LLM Studio tab", exc_info=True)
    return {"ok": True, "workspaces": found, "server_epoch": service.SERVER_EPOCH}


def stage_upload(raw: bytes, name: str = "") -> tuple[dict, int]:
    import mc_llm_attachment_staging as staging

    if len(raw) > MAX_UPLOAD:
        return {"ok": False, "error": {"code": service.INVALID_INPUT,
                                       "message": "That picture is larger than 20 MB.",
                                       "retryable": False}}, 413
    staged = staging.stage(raw, name)
    if not staged.ready:
        return {"ok": False, "state": staged.state, "reason": staged.reason,
                "error": {"code": service.INVALID_INPUT, "message": staged.reason,
                          "retryable": False}}, 422
    found = staged.describe()
    found["ok"] = True
    return found, 200


# --------------------------------------------------------------------------- #
# Registration
# --------------------------------------------------------------------------- #


def install(_demo=None, app=None) -> bool:
    """Register the routes on the WebUI's FastAPI app. Idempotent, never fatal.

    Signature is ``script_callbacks.on_app_started``'s. A UI reload calls it
    again and a second registration would give FastAPI two matching routes for
    one path, so the existing paths are looked for first -- the pattern
    ``mc_literal_report`` established and ``mc_voice_api`` follows.
    """
    global _installed

    if app is None or not hasattr(app, "add_api_route"):
        return False
    existing = {getattr(route, "path", None) for route in getattr(app, "routes", [])}
    if all(path in existing for path in ROUTES):
        _installed = True
        return True
    if Request is None:
        logger.debug("Model Chain: the conversation routes have no FastAPI to register on")
        return False

    async def bootstrap_route(request: Request):
        try:
            checked(request)
        except Refused as exc:
            return _refusal(exc)
        try:
            return _json(bootstrap(request.query_params.get("page") or ""))
        except Exception:
            return _failed("could not start a conversation session",
                           "The conversation could not be reached.")

    async def commands_route(request: Request):
        try:
            checked(request)
            body = await _body(request)
        except Refused as exc:
            return _refusal(exc)
        try:
            payload, status = commands(body)
            return _json(payload, status)
        except Exception:
            return _failed("a conversation command failed", "That could not be done.")

    async def snapshot_route(request: Request):
        try:
            checked(request)
        except Refused as exc:
            return _refusal(exc)
        query = request.query_params
        cursor = query.get("cursor")
        try:
            return _json(snapshot(query.get("character") or "", query.get("thread") or "",
                                  query.get("selection_epoch") or "",
                                  int(cursor) if cursor not in (None, "") else None))
        except Exception:
            return _failed("could not read a conversation",
                           "This conversation could not be read.")

    async def operation_route(request: Request):
        try:
            checked(request)
        except Refused as exc:
            return _refusal(exc)
        try:
            payload, status = operation(request.path_params.get("operation_id", ""))
            return _json(payload, status)
        except Exception:
            return _failed("could not read an operation", "That could not be looked up.")

    async def resolve_route(request: Request):
        try:
            checked(request)
            body = await _body(request)
        except Refused as exc:
            return _refusal(exc)
        import mc_llm_conversation_ops as ops

        try:
            return _json(ops.resolve(request.path_params.get("operation_id", ""),
                                     str(body.get("decision") or "")))
        except service.Refused as refusal:
            return _json({"ok": False, "error": refusal.payload()}, refusal.status)
        except Exception:
            return _failed("could not resolve an unsaved reply",
                           "That reply could not be dealt with.")

    async def subscribe_route(request: Request):
        try:
            checked(request)
            body = await _body(request)
        except Refused as exc:
            return _refusal(exc)
        try:
            return _json(subscribe(str(body.get("page_id") or "")))
        except Exception:
            return _failed("could not open a conversation feed",
                           "Live updates could not be started.")

    async def events_route(request: Request):
        try:
            checked(request)
        except Refused as exc:
            return _refusal(exc)
        query = request.query_params
        found = feed.find(query.get("feed") or "")
        if found is None:
            return _json({"ok": False, "error": {"code": service.SERVER_RESTARTED,
                                                 "message": "This feed is gone. Subscribe "
                                                            "again.", "retryable": False}},
                         409)
        cursor = query.get("cursor")
        if cursor not in (None, ""):
            try:
                found.cursor = int(cursor)
            except (TypeError, ValueError):
                pass

        def body():
            # A comment line on every idle pass. Proxies close connections that
            # say nothing, and two bytes every fifteen seconds is the cheapest
            # way to be sure a silence is ours rather than the network's.
            quiet = time.monotonic()
            yield b": open\n\n"
            for event in found.events(idle=STREAM_IDLE):
                quiet = time.monotonic()
                yield f"event: {event.get('kind')}\n".encode("utf-8")
                yield f"id: {event.get('stream_cursor')}\n".encode("utf-8")
                yield f"data: {json.dumps(event, ensure_ascii=False)}\n\n".encode("utf-8")
                if time.monotonic() - quiet > HEARTBEAT:
                    yield b": keep-alive\n\n"

        return StreamingResponse(body(), media_type="text/event-stream",
                                 headers={"Cache-Control": "no-cache, no-transform",
                                          "X-Accel-Buffering": "no",
                                          "Connection": "keep-alive"})

    async def attachments_route(request: Request):
        try:
            checked(request)
        except Refused as exc:
            return _refusal(exc)
        try:
            form = await request.form()
            upload = form.get("file")
            if upload is None:
                return _json({"ok": False, "error": {"code": service.INVALID_INPUT,
                                                     "message": "No picture was sent.",
                                                     "retryable": False}}, 400)
            raw = await upload.read()
            payload, status = stage_upload(raw, getattr(upload, "filename", "") or "")
            return _json(payload, status)
        except Exception:
            return _failed("could not stage an attachment",
                           "That picture could not be read.")

    async def attachment_delete_route(request: Request):
        try:
            checked(request)
        except Refused as exc:
            return _refusal(exc)
        import mc_llm_attachment_staging as staging

        return _json({"ok": staging.discard(request.path_params.get("token", ""))})

    async def workspaces_route(request: Request):
        try:
            checked(request)
        except Refused as exc:
            return _refusal(exc)
        return _json(workspaces())

    async def served_route(request: Request):
        """One stored picture, by ticket. The flyout's transcript reads these.

        A ticket rather than a path, because specification 6.6 is explicit that
        no filesystem path leaves the server -- and a route that took one would
        be a route somebody could hand a different one.
        """
        try:
            checked(request)
        except Refused as exc:
            return _refusal(exc)
        import mc_llm_attachments

        found = mc_llm_attachments.serving_path(request.path_params.get("ticket", ""))
        if found is None:
            return _json({"ok": False, "error": {"code": service.NOT_FOUND,
                                                 "message": "That picture is not there.",
                                                 "retryable": False}}, 404)
        try:
            return Response(content=found.read_bytes(),
                            media_type=_media_type(found.suffix),
                            headers={"Cache-Control": "private, max-age=3600"})
        except OSError:
            return _failed("could not read an attachment", "That picture could not be read.",
                           404)

    try:
        for path, handler, methods in (
                (BOOTSTRAP_ROUTE, bootstrap_route, ["GET"]),
                (COMMANDS_ROUTE, commands_route, ["POST"]),
                (SNAPSHOT_ROUTE, snapshot_route, ["GET"]),
                (OPERATION_ROUTE, operation_route, ["GET"]),
                (RESOLVE_ROUTE, resolve_route, ["POST"]),
                (SUBSCRIBE_ROUTE, subscribe_route, ["POST"]),
                (EVENTS_ROUTE, events_route, ["GET"]),
                (ATTACHMENTS_ROUTE, attachments_route, ["POST"]),
                (ATTACHMENT_ROUTE, attachment_delete_route, ["DELETE"]),
                (WORKSPACES_ROUTE, workspaces_route, ["GET"]),
                (SERVED_ROUTE, served_route, ["GET"])):
            if path not in existing:
                app.add_api_route(path, handler, methods=methods)
    except Exception:
        logger.debug("Model Chain: could not register the conversation routes", exc_info=True)
        return False
    _installed = True
    logger.info("Model Chain: Forge Assistant conversation routes registered at %s", PREFIX)
    return True


def _media_type(suffix: str) -> str:
    return {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
            ".webp": "image/webp", ".gif": "image/gif"}.get(suffix.lower(),
                                                            "application/octet-stream")


def installed() -> bool:
    return _installed
