"""One door into the conversation. Every writer comes through here.

The tab's Gradio callbacks and the assistant's HTTP routes are two ways of
saying the same sentences, and this module is where they become the same
sentence. A command arrives as an envelope — what to do, to which message of
which conversation, and *what revision the person was looking at when they
decided* — and leaves as an outcome that either happened exactly once or did
not happen at all.

Why an envelope rather than arguments
-------------------------------------
Three of its fields exist because of failures that have no other answer.

``expected_revision`` is the one the whole design turns on. An index alone is
not a target: "delete message 4" means a different message once another window
has inserted one, and the old code would have deleted whatever was at 4 by
then. Index and revision are validated *together*, under the conversation's
lock, so a target either names what the person saw or names nothing.

``operation_id`` is minted by the client before the first transmission and
never re-minted. A send whose acknowledgement is lost is retried with the same
id and produces one message and one inference — the second attempt finds the
receipt and returns the first attempt's answer. The same id with different
content is a bug in the caller and is refused rather than guessed at.

``server_epoch`` catches the case that looks like all the others and is not: a
restarted server. Operation ids from the old process mean nothing to the new
one, and a client that does not know it restarted would retry into a registry
that has never heard of its request. The epoch changes on restart, so it is
told.

What this module does not do
----------------------------
It does not build prompts, choose samplers, load models, decide who gets the
card, or speak. Those all stayed exactly where they were. What moved here is
only the deciding of whether a change is allowed and the recording of what
happened — which is the part that was never anywhere at all.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import threading
import time
import uuid
from dataclasses import dataclass, field

import mc_llm_conversation_store as store_module
from mc_llm_conversation_store import Key, Receipt, StoreRefusal

logger = logging.getLogger("model_chain")
"""Handler is attached once, in mc_memory."""

PROTOCOL_VERSION = 2

SERVER_EPOCH = uuid.uuid4().hex
"""This process's boot identity. Nonsecret, and regenerated by a restart.

Not a credential and never treated as one -- it is in every event and every
response, and its whole job is to let a page notice that the process it was
talking to is not the process it is talking to now.
"""

MAX_TEXT_BYTES = 256 * 1024
"""The largest message this will accept, in UTF-8 bytes. Refused, never cut.

Silent truncation is the failure mode this number exists to prevent: a message
that arrives shortened is a message the person did not write, and they find out
by reading their own conversation later.
"""

TERMINAL_RETENTION = 1800.0
"""How long a finished operation's outcome is remembered. Thirty minutes.

Long enough for any retry a dropped connection can produce, short enough that a
day of conversation is not also a day of receipts in RAM. The file's own
receipts outlive this and answer a retry after a restart.
"""

MAX_TERMINAL_RECORDS = 1000
"""Per scope. When full, new operations are refused rather than old ones evicted.

The order matters and is the specification's (6.4). Evicting the youngest
record to admit a new one would mean the retry most likely to arrive is the one
whose answer was just thrown away.
"""

# -- actions ---------------------------------------------------------------- #

CREATE_THREAD = "create_thread"
SEND = "send"
EDIT_MESSAGE = "edit_message"
REGENERATE = "regenerate"
CONTINUE = "continue"
RESEND_FROM_USER = "resend_from_user"
BRANCH = "branch"
SELECT_VERSION = "select_version"
DROP_VERSION = "drop_version"
DELETE_MESSAGE = "delete_message"
DELETE_FROM = "delete_from"
RENAME_THREAD = "rename_thread"
SET_RESPONSE_PREFIX = "set_response_prefix"
DELETE_THREAD = "delete_thread"
RESTORE_TO_DRAFT = "restore_to_draft"
STOP = "stop"

ACTIONS = (CREATE_THREAD, SEND, EDIT_MESSAGE, REGENERATE, CONTINUE, RESEND_FROM_USER,
           BRANCH, SELECT_VERSION, DROP_VERSION, DELETE_MESSAGE, DELETE_FROM,
           RENAME_THREAD, SET_RESPONSE_PREFIX, DELETE_THREAD, RESTORE_TO_DRAFT, STOP)
"""Every command, and nothing else is one.

Adding to this tuple is a compatible change; renaming anything in it is not,
because these strings reach a browser and come back.
"""

GENERATING = (SEND, REGENERATE, CONTINUE, RESEND_FROM_USER)
"""The four that end in a model being asked for words."""

KEEP, REPLACE, REMOVE = "keep", "replace", "remove"
IMAGE_ACTIONS = (KEEP, REPLACE, REMOVE)
"""What an edit does with the message's existing picture.

``keep`` is the default and an absent field means it. Absence has meant
*remove* in one shape of this code before, which is how an edited caption lost
the photograph it was a caption for.
"""

# -- error codes ------------------------------------------------------------ #

INVALID_INPUT = "INVALID_INPUT"
NOT_FOUND = "NOT_FOUND"
STALE_REVISION = "STALE_REVISION"
THREAD_BUSY = "THREAD_BUSY"
ATTACHMENT_NOT_READY = "ATTACHMENT_NOT_READY"
ATTACHMENT_EXPIRED = "ATTACHMENT_EXPIRED"
VISION_UNAVAILABLE = "VISION_UNAVAILABLE"
OPERATION_ID_REUSED = "OPERATION_ID_REUSED"
AUTH_REQUIRED = "AUTH_REQUIRED"
FORBIDDEN = "FORBIDDEN"
UNSUPPORTED_PROTOCOL = "UNSUPPORTED_PROTOCOL"
SERVER_RESTARTED = "SERVER_RESTARTED"
SAVE_FAILED = "SAVE_FAILED"
STORAGE_EXTERNALLY_CHANGED = "STORAGE_EXTERNALLY_CHANGED"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

STATUS = {
    INVALID_INPUT: 400,
    UNSUPPORTED_PROTOCOL: 400,
    AUTH_REQUIRED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    STALE_REVISION: 409,
    THREAD_BUSY: 409,
    OPERATION_ID_REUSED: 409,
    SERVER_RESTARTED: 409,
    ATTACHMENT_NOT_READY: 422,
    ATTACHMENT_EXPIRED: 422,
    VISION_UNAVAILABLE: 422,
    STORAGE_EXTERNALLY_CHANGED: 422,
    SAVE_FAILED: 500,
    SERVICE_UNAVAILABLE: 503,
}
"""Code to HTTP status. 413 is applied by the size check itself, which is the
one refusal that has to happen before the body is parsed."""

RETRYABLE = (SAVE_FAILED, SERVICE_UNAVAILABLE)
"""Which refusals are worth pressing the same button again for.

A stale revision is not one of them: the answer is a fresh snapshot and a new
decision, and a client that retried it automatically would be a client that
overwrites another window as soon as it is patient enough.
"""


class Refused(Exception):
    """A command that will not be run, with the reason a person can read."""

    def __init__(self, code: str, message: str, **detail):
        super().__init__(message)
        self.code = code
        self.message = message
        self.detail = detail

    @property
    def status(self) -> int:
        return STATUS.get(self.code, 400)

    def payload(self) -> dict:
        found = {"code": self.code, "message": self.message,
                 "retryable": self.code in RETRYABLE}
        found.update(self.detail)
        return found


# --------------------------------------------------------------------------- #
# The envelope
# --------------------------------------------------------------------------- #

_ID = re.compile(r"^[A-Za-z0-9_.:-]{1,128}$")
"""What an identifier may look like. Anything else is not one.

Applied to operation ids, page ids and thread ids alike. The characters left
out are the ones that mean something to a path or to a shell; the length bound
is what stops a megabyte of "id" reaching a dictionary key.
"""


def _text(value, field_name: str, limit: int = 4096) -> str:
    if value is None:
        return ""
    if not isinstance(value, str):
        raise Refused(INVALID_INPUT, f"{field_name} must be text.")
    if len(value.encode("utf-8")) > limit:
        raise Refused(INVALID_INPUT, f"{field_name} is too long.")
    return value


def _identifier(value, field_name: str, required: bool = True) -> str:
    found = _text(value, field_name, 256).strip()
    if not found:
        if required:
            raise Refused(INVALID_INPUT, f"{field_name} is required.")
        return ""
    if not _ID.match(found):
        raise Refused(INVALID_INPUT, f"{field_name} is not a valid identifier.")
    return found


@dataclass
class Envelope:
    """One command, validated into the shape the dispatcher can trust."""

    action: str
    operation_id: str
    conversation: Key | None = None
    expected_revision: object = None
    target_index: int | None = None
    target_version: int | None = None
    payload: dict = field(default_factory=dict)
    page_id: str = ""
    issued_at: str = ""
    selection_epoch: str = ""

    def digest(self) -> str:
        """What "the same request" means, for deduplication.

        Covers what the command *does* and nothing about who sent it: action,
        target, expected revision, settings and content. ``page_id`` and
        ``selection_epoch`` are deliberately outside it, so that a retry after
        a refresh -- which is a different page with the same intention -- is
        recognised as the same request rather than refused as a reused id.
        """
        material = {
            "action": self.action,
            "conversation": [self.conversation.character, self.conversation.thread_id]
            if self.conversation else None,
            "expected_revision": self.expected_revision,
            "target": [self.target_index, self.target_version],
            "payload": {key: self.payload[key] for key in sorted(self.payload)
                        if key not in ("selection_epoch",)},
        }
        raw = json.dumps(material, sort_keys=True, ensure_ascii=False, default=str)
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def parse(body: dict) -> Envelope:
    """One request body, validated. Raises :class:`Refused` and never guesses.

    Every branch below refuses rather than repairing. A field this does not
    understand is not ignored: an unknown key that changes meaning is exactly
    how a newer client's "and also delete the rest" would be silently dropped
    by an older server and read as a plain edit.
    """
    if not isinstance(body, dict):
        raise Refused(INVALID_INPUT, "The request was not an object.")

    version = body.get("protocol_version")
    if version != PROTOCOL_VERSION:
        raise Refused(UNSUPPORTED_PROTOCOL,
                      "This page is a different version from the server. Reload the page.")

    epoch = body.get("server_epoch")
    if epoch is not None and str(epoch) != SERVER_EPOCH:
        raise Refused(SERVER_RESTARTED,
                      "The server restarted. Reload the page to carry on.")

    unknown = set(body) - {"protocol_version", "server_epoch", "operation_id", "issued_at",
                           "page_id", "conversation", "expected_revision", "action",
                           "target", "payload", "selection_epoch"}
    if unknown:
        raise Refused(INVALID_INPUT,
                      f"The request carried fields this server does not understand: "
                      f"{', '.join(sorted(unknown))}.")

    action = _text(body.get("action"), "action", 64)
    if action not in ACTIONS:
        raise Refused(INVALID_INPUT, f"{action or 'That'} is not something this can do.")

    operation_id = _identifier(body.get("operation_id"), "operation_id")
    page_id = _identifier(body.get("page_id"), "page_id", required=False)
    issued_at = _text(body.get("issued_at"), "issued_at", 64)

    conversation = None
    raw_conversation = body.get("conversation")
    if raw_conversation is not None:
        if not isinstance(raw_conversation, dict):
            raise Refused(INVALID_INPUT, "conversation must be an object.")
        conversation = Key(
            character=_text(raw_conversation.get("character"), "character", 256),
            thread_id=_identifier(raw_conversation.get("thread_id"), "thread_id",
                                  required=action != CREATE_THREAD),
        )
    if conversation is None and action != CREATE_THREAD:
        raise Refused(INVALID_INPUT, "conversation is required.")
    if conversation is not None and not str(conversation.character or "").strip():
        raise Refused(INVALID_INPUT, "character is required.")

    expected = _expected(body.get("expected_revision"), action)
    index, version_at = _target(body.get("target"))
    payload = _payload(body.get("payload"), action)

    return Envelope(action=action, operation_id=operation_id, conversation=conversation,
                    expected_revision=expected, target_index=index,
                    target_version=version_at, payload=payload, page_id=page_id,
                    issued_at=issued_at,
                    selection_epoch=_text(body.get("selection_epoch"),
                                          "selection_epoch", 128))


def _expected(raw, action: str):
    """``expected_revision`` as a comparison token, or a refusal.

    ``None`` is allowed only where there is nothing yet to compare against:
    creating a thread, and stopping an operation, which does not write.
    Everywhere else an absent token would mean "write over whatever is there",
    which is the behaviour this whole module replaced.
    """
    if raw is None:
        if action in (CREATE_THREAD, STOP):
            return None
        raise Refused(INVALID_INPUT, "expected_revision is required.")
    if not isinstance(raw, dict):
        raise Refused(INVALID_INPUT, "expected_revision must be an object.")
    kind = raw.get("kind")
    if kind == "revision":
        value = raw.get("value")
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise Refused(INVALID_INPUT, "expected_revision.value must be a revision.")
        return value
    if kind == "legacy":
        found = _text(raw.get("fingerprint"), "fingerprint", 256)
        if not found:
            raise Refused(INVALID_INPUT, "expected_revision.fingerprint is required.")
        return found
    raise Refused(INVALID_INPUT, "expected_revision.kind must be 'revision' or 'legacy'.")


def _target(raw):
    if raw is None:
        return None, None
    if not isinstance(raw, dict):
        raise Refused(INVALID_INPUT, "target must be an object.")
    index = raw.get("index")
    if isinstance(index, bool) or not isinstance(index, int) or index < 0:
        raise Refused(INVALID_INPUT, "target.index must be a message index.")
    version = raw.get("version")
    if version is not None and (isinstance(version, bool) or not isinstance(version, int)
                                or version < 0):
        raise Refused(INVALID_INPUT, "target.version must be a version number.")
    return index, version


def _payload(raw, action: str) -> dict:
    if raw is None:
        return {}
    if not isinstance(raw, dict):
        raise Refused(INVALID_INPUT, "payload must be an object.")
    found: dict = {}
    if "text" in raw:
        found["text"] = _text(raw.get("text"), "text", MAX_TEXT_BYTES)
    if "attachment_token" in raw:
        found["attachment_token"] = _identifier(raw.get("attachment_token"),
                                                "attachment_token", required=False)
    if "image_action" in raw:
        chosen = _text(raw.get("image_action"), "image_action", 16)
        if chosen not in IMAGE_ACTIONS:
            raise Refused(INVALID_INPUT, "image_action must be keep, replace or remove.")
        found["image_action"] = chosen
    if "title" in raw:
        found["title"] = _text(raw.get("title"), "title", 4096)
    if "prefix" in raw:
        found["prefix"] = _text(raw.get("prefix"), "prefix", 16 * 1024)
    if "confirm_count" in raw:
        count = raw.get("confirm_count")
        if isinstance(count, bool) or not isinstance(count, int) or count < 0:
            raise Refused(INVALID_INPUT, "confirm_count must be a count.")
        found["confirm_count"] = count
    if "confirm_title" in raw:
        found["confirm_title"] = _text(raw.get("confirm_title"), "confirm_title", 4096)
    if "operation_id" in raw:
        found["operation_id"] = _identifier(raw.get("operation_id"), "operation_id",
                                            required=action == STOP)
    if "voice" in raw:
        found["voice"] = bool(raw.get("voice"))
    if "settings" in raw:
        found["settings"] = _settings(raw.get("settings"))
    unknown = set(raw) - set(found) - {"settings"}
    if unknown:
        raise Refused(INVALID_INPUT,
                      f"payload carried fields this server does not understand: "
                      f"{', '.join(sorted(unknown))}.")
    return found


def _settings(raw) -> dict:
    if raw is None:
        return {}
    if not isinstance(raw, dict):
        raise Refused(INVALID_INPUT, "settings must be an object.")
    allowed = {"temperature", "top_p", "reply_tokens", "seed"}
    unknown = set(raw) - allowed
    if unknown:
        raise Refused(INVALID_INPUT,
                      f"settings carried fields this server does not understand: "
                      f"{', '.join(sorted(unknown))}.")
    found = {}
    for name in sorted(allowed & set(raw)):
        value = raw.get(name)
        if value is None:
            continue
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise Refused(INVALID_INPUT, f"settings.{name} must be a number.")
        found[name] = value
    return found


# --------------------------------------------------------------------------- #
# Deduplication
# --------------------------------------------------------------------------- #

PENDING = "pending"
ACCEPTED = "accepted"
DONE = "done"
REFUSED = "refused"


@dataclass
class Record:
    """What is known about one operation id in this process."""

    operation_id: str
    digest: str
    state: str = PENDING
    outcome: dict = field(default_factory=dict)
    settled: float = 0.0
    pinned: bool = False


class _Registry:
    """Operation ids and their outcomes, per access scope.

    Reserved *before* any mutation, which is the ordering the whole guarantee
    rests on: a second request carrying the same id finds the reservation and
    waits for or returns its answer, rather than racing it into the store.

    Checked before the revision comparison, deliberately (6.4). A retry of a
    request that was already accepted must not be told its revision is stale --
    it *is* stale, because the request itself is what moved it.
    """

    def __init__(self):
        self._guard = threading.Lock()
        self._scopes: dict[str, dict[str, Record]] = {}

    def reserve(self, scope: str, operation_id: str, digest: str) -> tuple[Record, bool]:
        """``(record, fresh)``. ``fresh`` is whether this caller owns the work."""
        with self._guard:
            records = self._scopes.setdefault(scope, {})
            self._expire(records)
            found = records.get(operation_id)
            if found is not None:
                if found.digest != digest:
                    raise Refused(OPERATION_ID_REUSED,
                                  "That request id has already been used for a different "
                                  "request.")
                return found, False
            terminal = sum(1 for record in records.values() if record.state in (DONE, REFUSED))
            if terminal >= MAX_TERMINAL_RECORDS:
                raise Refused(SERVICE_UNAVAILABLE,
                              "Too many recent requests are still being remembered. "
                              "Try again shortly.")
            record = records[operation_id] = Record(operation_id=operation_id, digest=digest,
                                                    pinned=True)
            return record, True

    def settle(self, scope: str, operation_id: str, state: str, outcome: dict) -> None:
        with self._guard:
            record = self._scopes.setdefault(scope, {}).get(operation_id)
            if record is None:
                return
            record.state = state
            record.outcome = outcome
            record.pinned = state == ACCEPTED
            record.settled = time.time()

    def find(self, scope: str, operation_id: str) -> Record | None:
        with self._guard:
            records = self._scopes.get(scope, {})
            self._expire(records)
            return records.get(operation_id)

    def drop(self, scope: str, operation_id: str) -> None:
        with self._guard:
            self._scopes.get(scope, {}).pop(operation_id, None)

    @staticmethod
    def _expire(records: dict) -> None:
        now = time.time()
        for key in [key for key, record in records.items()
                    if not record.pinned and record.settled
                    and now - record.settled > TERMINAL_RETENTION]:
            records.pop(key, None)

    def reset(self) -> None:
        """Drop every record. For the tests, and for a UI reload."""
        with self._guard:
            self._scopes.clear()


registry = _Registry()


DEFAULT_SCOPE = "local"
"""The access scope when the host has not told us about more than one.

Present as a parameter everywhere rather than assumed, because the day this
extension is put behind a multi-user proxy is the day an operation registry
shared between people becomes a way to read somebody else's reply.
"""


# --------------------------------------------------------------------------- #
# Stores
# --------------------------------------------------------------------------- #


def chats():
    from prompt_master.chat.history import ChatStore

    import mc_llm_paths

    return ChatStore.from_paths(mc_llm_paths.app_paths())


def _characters():
    from prompt_master.chat.characters import CharacterStore

    import mc_llm_paths

    return CharacterStore.from_paths(mc_llm_paths.app_paths())


# --------------------------------------------------------------------------- #
# Dispatch
# --------------------------------------------------------------------------- #


def submit(body: dict, scope: str = DEFAULT_SCOPE) -> dict:
    """One command, from anywhere. The only entry point that writes.

    Returns the response of specification 6.7 rather than raising, because both
    callers -- a Gradio callback and an HTTP route -- have to turn a refusal
    into something on a screen and neither benefits from an exception crossing
    the boundary first.
    """
    try:
        envelope = parse(body)
    except Refused as refusal:
        return _failed(refusal, body.get("operation_id") if isinstance(body, dict) else None)
    return run(envelope, scope)


def run(envelope: Envelope, scope: str = DEFAULT_SCOPE) -> dict:
    """A validated envelope, executed exactly once."""
    try:
        record, fresh = registry.reserve(scope, envelope.operation_id, envelope.digest())
    except Refused as refusal:
        return _failed(refusal, envelope.operation_id)
    if not fresh:
        if record.state in (DONE, ACCEPTED):
            found = dict(record.outcome)
            found["duplicate"] = True
            return found
        if record.state == REFUSED:
            found = dict(record.outcome)
            found["duplicate"] = True
            return found
        return {"ok": True, "operation_id": envelope.operation_id, "phase": PENDING,
                "duplicate": True, "persisted": False, "server_epoch": SERVER_EPOCH}

    try:
        outcome = _dispatch(envelope, scope)
    except Refused as refusal:
        failure = _failed(refusal, envelope.operation_id)
        registry.settle(scope, envelope.operation_id, REFUSED, failure)
        return failure
    except StoreRefusal as refusal:
        failure = _failed(_from_store(refusal), envelope.operation_id)
        registry.settle(scope, envelope.operation_id, REFUSED, failure)
        return failure
    except Exception as exc:
        logger.warning("Model Chain: a conversation command failed", exc_info=True)
        failure = _failed(Refused(SAVE_FAILED, f"That could not be done: {exc}"),
                          envelope.operation_id)
        registry.settle(scope, envelope.operation_id, REFUSED, failure)
        return failure
    # Only a generating command leaves something running to pin a record for.
    # Everything else is finished the moment it returns, and a record settled as
    # ACCEPTED is pinned -- so settling a Stop or a rename that way would leave
    # a record that never expires and is not counted against the terminal cap
    # either, which is an unbounded one.
    live = envelope.action in GENERATING and outcome.get("phase") not in (None, "completed")
    registry.settle(scope, envelope.operation_id, ACCEPTED if live else DONE, outcome)
    return outcome


def _from_store(refusal: StoreRefusal) -> Refused:
    return Refused(getattr(refusal, "code", SAVE_FAILED), str(refusal),
                   **{key: value for key, value in (getattr(refusal, "detail", None) or {}).items()
                      if value is not None})


def _failed(refusal: Refused, operation_id) -> dict:
    return {"ok": False, "operation_id": str(operation_id or ""), "persisted": False,
            "duplicate": False, "phase": "failed", "server_epoch": SERVER_EPOCH,
            "error": refusal.payload(), "status": refusal.status}


def _accepted(envelope: Envelope, key: Key, revision: int, phase: str = "completed",
              persisted: bool = True, extra: dict | None = None) -> dict:
    found = {"ok": True, "operation_id": envelope.operation_id, "persisted": persisted,
             "duplicate": False, "phase": phase, "server_epoch": SERVER_EPOCH,
             "accepted_revision": envelope.expected_revision,
             "resulting_conversation": {"character": key.character,
                                        "thread_id": key.thread_id},
             "revision": revision}
    if extra:
        found.update(extra)
    return found


def _dispatch(envelope: Envelope, scope: str) -> dict:
    if envelope.action == STOP:
        return _stop(envelope)
    if envelope.action == CREATE_THREAD:
        return _create_thread(envelope)
    if envelope.action == DELETE_THREAD:
        return _delete_thread(envelope)
    if envelope.action == BRANCH:
        return _branch(envelope)
    if envelope.action in GENERATING:
        import mc_llm_conversation_ops as ops

        return ops.begin(envelope, scope)
    return _mutate(envelope)


# -- the plain content mutations -------------------------------------------- #


def _mutate(envelope: Envelope) -> dict:
    store = chats()
    key = envelope.conversation
    receipt = Receipt(operation_id=envelope.operation_id, action=envelope.action,
                      issued_at=envelope.issued_at, payload_digest=envelope.digest())

    def change(conversation):
        return _apply(envelope, conversation)

    committed = store_module.transaction(store, key, envelope.expected_revision, change,
                                         receipt=receipt)
    if committed.duplicate:
        return _accepted(envelope, key, committed.revision,
                         extra={"duplicate": True, "receipt": committed.receipt})
    return _accepted(envelope, key, committed.revision,
                     extra={"detail": committed.result if isinstance(committed.result, dict)
                            else None})


def _apply(envelope: Envelope, conversation) -> object:
    """One action, against the copy the transaction will write. May raise.

    Every branch validates its target against *this* conversation -- the one
    read under the lock -- rather than against whatever the caller described.
    That is the second half of the (index, revision) promise: the revision says
    the conversation has not moved, and this says the index names a message in
    it of the role the action applies to.
    """
    action = envelope.action
    if action == EDIT_MESSAGE:
        return _edit(envelope, conversation)
    if action == SELECT_VERSION:
        message = _message(envelope, conversation)
        wanted = envelope.target_version
        if wanted is None:
            raise Refused(INVALID_INPUT, "Which version?")
        if not 0 <= wanted < len(message.versions):
            raise Refused(INVALID_INPUT, "That version is not there any more.")
        message.show(wanted)
        return {"active": message.active, "versions": len(message.versions)}
    if action == DROP_VERSION:
        message = _message(envelope, conversation)
        if len(message.versions) <= 1:
            raise Refused(INVALID_INPUT,
                          "This message has only one version — deleting it would delete "
                          "the message.")
        message.drop_version()
        return {"active": message.active, "versions": len(message.versions)}
    if action == DELETE_MESSAGE:
        _message(envelope, conversation)
        conversation.delete(envelope.target_index)
        return {"removed": 1}
    if action == DELETE_FROM:
        _message(envelope, conversation)
        removed = len(conversation.messages) - envelope.target_index
        wanted = envelope.payload.get("confirm_count")
        if wanted is not None and wanted != removed:
            raise Refused(STALE_REVISION,
                          f"That would now delete {removed} messages, not {wanted}.")
        conversation.delete_from(envelope.target_index)
        return {"removed": removed}
    if action == RENAME_THREAD:
        title = (envelope.payload.get("title") or "").strip()
        if not title:
            raise Refused(INVALID_INPUT, "A thread needs a title.")
        conversation.title = title
        return {"title": title}
    if action == SET_RESPONSE_PREFIX:
        conversation.response_prefix = envelope.payload.get("prefix") or ""
        return {"prefix": conversation.response_prefix}
    if action == RESTORE_TO_DRAFT:
        return _restore_to_draft(envelope, conversation)
    raise Refused(INVALID_INPUT, f"{action} is not something this can do here.")


def _message(envelope: Envelope, conversation, role: str | None = None):
    index = envelope.target_index
    if index is None:
        raise Refused(INVALID_INPUT, "Which message?")
    if not 0 <= index < len(conversation.messages):
        raise Refused(STALE_REVISION, "That message is not there any more.")
    message = conversation.messages[index]
    if role is not None and message.role != role:
        raise Refused(INVALID_INPUT, "That action does not apply to this message.")
    return message


def _edit(envelope: Envelope, conversation) -> dict:
    """Edit one message in place, at any index, and say what it did.

    In place is the behaviour, unchanged (4.2): the words in the thread change,
    the thread stays where it is, and the replies that followed are still under
    it. Descendants are not regenerated and the editor says so -- a rewritten
    question with the old answer under it is a conversation somebody can then
    ask about, and silently re-running the model would be an edit that costs a
    GPU minute nobody asked for.
    """
    import mc_llm_attachments

    message = _message(envelope, conversation)
    version = envelope.target_version
    if version is not None:
        if not 0 <= version < len(message.versions):
            raise Refused(STALE_REVISION, "That version is not there any more.")
        message.active = version
    message.text = (envelope.payload.get("text") or "").strip()

    wanted = envelope.payload.get("image_action", KEEP)
    if wanted == REMOVE:
        message.image_path, message.image, message.image_name = "", "", ""
    elif wanted == REPLACE:
        token = envelope.payload.get("attachment_token") or ""
        import mc_llm_attachment_staging as staging

        staged = staging.resolve(token)
        if staged is None:
            raise Refused(ATTACHMENT_EXPIRED, "Attach this image again.")
        try:
            message.image_path = mc_llm_attachments.store(staged.image,
                                                          conversation.character)
        except Exception as exc:
            raise Refused(SAVE_FAILED, f"Could not keep that picture: {exc}")
        message.image = ""
        message.image_name = staged.name
    return {"index": envelope.target_index, "image_action": wanted}


def _restore_to_draft(envelope: Envelope, conversation) -> dict:
    """The unanswered-message lift, as a command somebody asked for.

    It already happened -- opening a thread that ended in an unanswered message
    took it out of the thread and put it back in the composer, and *saved*.
    Navigation wrote. That is kept, because it is what the owner asked for and
    people rely on it, but it is a command now: the read-only refresh that keeps
    a second window current can never reach it, which it could when it was a
    side effect of ``_open_thread``.
    """
    from prompt_master.chat.history import USER

    index = envelope.target_index
    if index is None or not 0 <= index < len(conversation.messages):
        raise Refused(STALE_REVISION, "That message is not there any more.")
    message = conversation.messages[index]
    if message.role != USER or index != len(conversation.messages) - 1:
        raise Refused(INVALID_INPUT, "Only an unanswered last message can be taken back.")
    if message.attached:
        raise Refused(INVALID_INPUT,
                      "This message carries a picture, so it stays in the thread. "
                      "Edit it, or send it again from here.")
    text = message.text
    conversation.delete_from(index)
    return {"text": text}


# -- the ones that are not one file ----------------------------------------- #


def _create_thread(envelope: Envelope) -> dict:
    store = chats()
    character = envelope.conversation.character if envelope.conversation else ""
    if not str(character).strip():
        raise Refused(INVALID_INPUT, "Choose a character first.")
    identifier = store.new(character).identifier
    key = Key(character=character, thread_id=identifier)
    receipt = Receipt(operation_id=envelope.operation_id, action=envelope.action,
                      issued_at=envelope.issued_at, payload_digest=envelope.digest(),
                      resulting_conversation=identifier)

    def build():
        from prompt_master.chat.history import ASSISTANT, Conversation

        now = time.time()
        conversation = Conversation(identifier=identifier, character=character,
                                    created=now, updated=now)
        text = _greeting(character)
        if text.strip():
            conversation.append(ASSISTANT, text)
        return conversation

    committed = store_module.create(store, key, build, receipt=receipt)
    publish(CONVERSATION_CHANGED, key, revision=committed.revision, kind_detail="created")
    return _accepted(envelope, key, committed.revision)


def _greeting(character: str) -> str:
    from prompt_master.chat.prompt import greeting_text

    try:
        from prompt_master.chat.characters import load_persona

        import mc_llm_paths

        return greeting_text(_characters().load(character),
                             load_persona(mc_llm_paths.app_paths()))
    except Exception:
        logger.debug("Model Chain: could not read %s's greeting", character, exc_info=True)
        return ""


def _delete_thread(envelope: Envelope) -> dict:
    store = chats()
    key = envelope.conversation
    wanted = envelope.payload.get("confirm_title")
    if wanted is not None:
        conversation, _ = store_module.read(store, key)
        if conversation.title != wanted:
            raise Refused(STALE_REVISION, "This thread was renamed. Look again before "
                                          "deleting it.")
    receipt = Receipt(operation_id=envelope.operation_id, action=envelope.action,
                      issued_at=envelope.issued_at, payload_digest=envelope.digest())
    store_module.remove(store, key, envelope.expected_revision, receipt=receipt)
    publish(THREAD_DELETED, key)
    return _accepted(envelope, key, 0)


def _branch(envelope: Envelope) -> dict:
    """Copy a thread through one message into a new one. Two files, one lock order.

    The source is read and left alone -- a branch never writes to the thread it
    came from, which is what makes every one of these actions reversible by
    simply going back to it.
    """
    store = chats()
    key = envelope.conversation
    index = envelope.target_index
    committed = _branch_from(store, key, envelope.expected_revision, index,
                             envelope.operation_id, envelope.issued_at, envelope.digest())
    branched = committed.conversation
    made = Key(character=branched.character, thread_id=branched.identifier)
    publish(THREAD_CREATED, made, revision=committed.revision)
    return _accepted(envelope, made, committed.revision)


def _branch_from(store, key: Key, expected, index: int, operation_id: str,
                 issued_at: str, digest: str):
    """The shared half of every branching action. Returns the new conversation.

    Used by Branch from here, by mid-thread Regenerate, by Continue on an
    earlier reply and by Send again from here -- four buttons that used to be
    four pieces of nearly-identical code, one of which deleted the rest of the
    conversation (specification 6.3).
    """
    source, raw = store_module.read(store, key)
    if source.damaged:
        raise Refused(STORAGE_EXTERNALLY_CHANGED, "Conversation metadata needs repair.")
    current = store_module.token_of(source, raw)
    if not store_module.matches(expected, current):
        raise Refused(STALE_REVISION, "This conversation changed in another window. "
                                      "Your draft is safe.", current_revision=current)
    owner = store_module.active_writer(store, key)
    if owner:
        raise Refused(THREAD_BUSY, "Reply in progress. Stop it before changing this "
                                   "conversation.", operation_id=owner.get("operation_id"))
    if index is None or not -1 <= index < len(source.messages):
        raise Refused(STALE_REVISION, "That message is not there any more.")

    identifier = store.new(key.character).identifier
    made = Key(character=key.character, thread_id=identifier)
    receipt = Receipt(operation_id=operation_id, action=BRANCH, issued_at=issued_at,
                      payload_digest=digest, resulting_conversation=identifier)
    return store_module.create(store, made,
                               lambda: source.branch(index, identifier), receipt=receipt)


def _stop(envelope: Envelope) -> dict:
    import mc_llm_conversation_ops as ops

    wanted = envelope.payload.get("operation_id") or ""
    stopped = ops.stop(wanted)
    return {"ok": True, "operation_id": envelope.operation_id, "persisted": False,
            "duplicate": False, "phase": "stopping" if stopped else "unknown",
            "server_epoch": SERVER_EPOCH, "stopped": wanted}


# --------------------------------------------------------------------------- #
# Snapshots
# --------------------------------------------------------------------------- #


def snapshot(character: str, thread_id: str, selection_epoch: str = "",
             cursor: int | None = None) -> dict:
    """The whole displayed truth about one conversation, at one moment.

    Read-only, and the *only* way a second window learns what the first one
    did. It carries no filesystem path: an attachment is a name, an availability
    and the serving route the tab already uses, because a browser that is handed
    a path is a browser that can be persuaded to ask for a different one.
    """
    store = chats()
    key = Key(character=character or "", thread_id=thread_id or "")
    import mc_llm_conversation_feed as feed

    found: dict = {
        "protocol_version": PROTOCOL_VERSION,
        "capabilities": capabilities(),
        "sync": {"server_epoch": SERVER_EPOCH,
                 "stream_cursor": feed.cursor() if cursor is None else int(cursor)},
        "selection_epoch": selection_epoch or "",
        "operation": None,
    }
    if not key.valid:
        found["conversation"] = None
        found["messages"] = []
        return found
    try:
        conversation, raw = store_module.read(store, key)
    except StoreRefusal as refusal:
        found["conversation"] = None
        found["messages"] = []
        found["error"] = _from_store(refusal).payload()
        return found

    found["conversation"] = {
        "character": conversation.character,
        "thread_id": conversation.identifier,
        "title": conversation.title,
        "revision": store_module.token_of(conversation, raw),
        "response_prefix": conversation.response_prefix,
        "updated": conversation.updated,
        "damaged": bool(conversation.damaged),
    }
    found["messages"] = [_message_view(index, message)
                         for index, message in enumerate(conversation.messages)]

    found["threads"] = threads(character)
    found["characters"] = character_names()

    import mc_llm_conversation_ops as ops

    running = ops.for_conversation(key)
    if running is not None:
        found["operation"] = running.describe()
    found["recovery"] = [item.describe() for item in ops.recoverable(key)]
    return found


def _message_view(index: int, message) -> dict:
    import mc_llm_attachments

    attachment = None
    if message.attached:
        available = True
        if message.image_path:
            try:
                available = mc_llm_attachments.locate(message.image_path) is not None
            except Exception:
                available = False
        attachment = {"name": message.image_name or "", "available": bool(available),
                      "inline": bool(message.image and not message.image_path)}
        if message.image_path:
            attachment["url"] = mc_llm_attachments.serving_url(message.image_path)
    return {"index": index, "role": message.role, "versions": list(message.versions),
            "active": message.active, "text": message.text, "attachment": attachment}


def capabilities() -> dict:
    """What this installation can do right now, as the flyout needs to know it."""
    vision = False
    try:
        import mc_llm_runtime

        vision = bool(mc_llm_runtime.config().sees)
    except Exception:
        logger.debug("Model Chain: could not read the vision configuration", exc_info=True)
    voice = False
    try:
        import mc_voice_state

        voice = bool(mc_voice_state.enabled())
    except Exception:
        logger.debug("Model Chain: could not read the voice configuration", exc_info=True)
    return {"actions": list(ACTIONS), "vision": vision, "upload": True,
            "voice": voice, "streaming": True,
            "protocol_version": PROTOCOL_VERSION, "max_text_bytes": MAX_TEXT_BYTES}


def bootstrap(page_id: str = "") -> dict:
    """What a page needs before it can show anything, including *which* thread.

    The selection is the part that was missing, and without it the flyout had
    nothing to draw: it opened with an empty character and an empty thread, the
    snapshot call returned early because there was nothing to snapshot, and the
    panel sat on "Reconnecting…" for ever with a transcript it was never going
    to be given.

    It is a *seed* and not a source of truth -- ``mc_llm_state.remember()`` is
    installation-wide, so it says which conversation was last opened on this
    machine, not which one this page is looking at. The page owns its selection
    from here on (two windows may deliberately differ), and this is only how it
    starts out on the one the tab has open.
    """
    return {"protocol_version": PROTOCOL_VERSION, "server_epoch": SERVER_EPOCH,
            "server_time": time.time(), "capabilities": capabilities(),
            "page_id": page_id or uuid.uuid4().hex, "actions": list(ACTIONS),
            "selection": remembered_selection(),
            "characters": character_names(),
            "mode": remembered_mode(),
            "read_aloud": read_aloud()}


def read_aloud():
    """Whether replies are read aloud: Voice Chat's "Speak replies
    automatically", the one setting both views share. ``None`` if it cannot be
    read.

    The flyout's switch is drawn from this. It used to start "off" whatever the
    setting was and never ask, so a first press on a switch that read off
    turned on something already on -- and the replies went on being spoken.
    ``None`` rather than ``False`` when unreadable, because "off" is a claim and
    a switch that makes one it cannot back is the bug this replaces.
    """
    try:
        import mc_voice_state

        return bool(mc_voice_state.auto_speak())
    except Exception:
        logger.debug("Model Chain: could not read whether replies are read aloud",
                     exc_info=True)
        return None


def remembered_selection() -> dict:
    """The character and thread LLM Studio was last left on."""
    try:
        import mc_llm_state

        found = mc_llm_state.preferences()
        return {"character": str(found.get("character") or ""),
                "thread_id": str(found.get("thread") or "")}
    except Exception:
        logger.debug("Model Chain: could not read the remembered conversation",
                     exc_info=True)
        return {"character": "", "thread_id": ""}


def remembered_mode() -> str:
    try:
        import mc_llm_state

        return str(mc_llm_state.preferences().get("mode") or "")
    except Exception:
        return ""


def character_names() -> list:
    try:
        return list(_characters().names())
    except Exception:
        logger.debug("Model Chain: could not list characters", exc_info=True)
        return []


def threads(character: str) -> list:
    """The character's threads, most recently used first."""
    try:
        return [{"thread_id": info.identifier, "title": info.title,
                 "updated": info.updated}
                for info in chats().listing(str(character or ""))]
    except Exception:
        logger.debug("Model Chain: could not list threads for %s", character,
                     exc_info=True)
        return []


# --------------------------------------------------------------------------- #
# Publishing
# --------------------------------------------------------------------------- #

SNAPSHOT = "snapshot"
CONVERSATION_CHANGED = "conversation_changed"
THREAD_CREATED = "thread_created"
THREAD_DELETED = "thread_deleted"
CHARACTER_CHANGED = "character_changed"
MODE_CHANGED = "mode_changed"
OPERATION_ACCEPTED = "operation_accepted"
OPERATION_PHASE = "operation_phase"
REPLY_PATCH = "reply_patch"
OPERATION_TERMINAL = "operation_terminal"
RESULT_CONFLICT = "result_conflict"
SPEECH_STATE = "speech_state"
RESET_REQUIRED = "reset_required"
CAPABILITIES_CHANGED = "capabilities_changed"

KINDS = (SNAPSHOT, CONVERSATION_CHANGED, THREAD_CREATED, THREAD_DELETED, CHARACTER_CHANGED,
         MODE_CHANGED, OPERATION_ACCEPTED, OPERATION_PHASE, REPLY_PATCH, OPERATION_TERMINAL,
         RESULT_CONFLICT, SPEECH_STATE, RESET_REQUIRED, CAPABILITIES_CHANGED)


def publish(kind: str, key: Key | None = None, **payload) -> None:
    """Tell every open page that something happened. Never fails a caller.

    Display publishing fails *open* (specification 4.4) and safety fails
    closed, and this is the open half: a save that succeeded is a save that
    succeeded whether or not anybody could be told about it. A publish that
    raises here would make a successful write look like a failed one, which is
    the one thing worse than a window that has to be refreshed.
    """
    try:
        import mc_llm_conversation_feed as feed

        feed.publish(kind, key, **payload)
    except Exception:
        logger.debug("Model Chain: could not publish a conversation event", exc_info=True)


def reset() -> None:
    """Forget every operation record. For the tests, and for a UI reload."""
    registry.reset()
