"""The four browser routes, on the WebUI's own app, under the WebUI's own auth.

Voice Chat adds no second web server. The browser already has a connection to
Forge -- often an HTTPS one across a LAN, because that is what an Android
microphone requires -- and these routes ride on it:

    POST <root>/model-chain/voice/status    what is installed, what is ready
    POST <root>/model-chain/voice/stt       a PCM16 WAV in, a transcript out
    POST <root>/model-chain/voice/tts       a target token in, a WAV out
    POST <root>/model-chain/voice/install   provision one of the two bundles

``<root>`` is the point of R2-4 and is not this module's problem: FastAPI mounts
these where the app is mounted, and ``javascript/voice_chat.js`` builds its URLs
from the deployment root Gradio publishes rather than from ``location.origin``.
What *is* this module's problem is proving they are no more reachable than the
rest of the WebUI, and there are three separate reasons for that:

Authentication parity
    Sharing a FastAPI app is not the same as inheriting Gradio's login. Gradio
    protects its own endpoints with a dependency it does not apply to routes an
    extension adds, so an extension route on an authenticated WebUI is an open
    route unless somebody makes it otherwise. :func:`_authorised` is that
    somebody: when the host has auth configured, a caller must present a session
    cookie Gradio itself issued, or it gets 401.

The page token
    A per-process random value the page is given by Python and sends back in
    ``X-Model-Chain-Voice``. It is not a login and does not pretend to be one --
    it makes a cross-site page unable to drive these routes with the user's
    cookies, and it makes a stale tab from before a restart fail cleanly rather
    than confusingly.

Speech targets
    The TTS route takes a token, never text. What it speaks is an immutable
    snapshot of the assistant reply that completed the run which created the
    target (R2-5) -- so editing, regenerating, branching or switching threads
    between the reply and the request cannot change what comes out of the
    speaker. Targets are one-shot, expire in two minutes, live in this process's
    RAM, and are never written down or logged.

Nothing here touches the disk. The uploaded WAV is a ``bytes`` that goes to the
worker and is dropped; the generated WAV is a response body. There is no
``/file=`` URL, no Gradio audio cache, and no ``tempfile`` import in this module
-- which is a thing ``tests/test_voice_privacy.py`` checks rather than a thing
this docstring merely asserts.
"""

from __future__ import annotations

import logging
import secrets
import struct
import threading
import time

import mc_voice_models as models
import mc_voice_paths as paths
import mc_voice_runtime as runtime
import mc_voice_state as state

try:
    from fastapi import Request, Response
    from fastapi.responses import JSONResponse
except Exception:  # pragma: no cover - a host without FastAPI has no routes to add
    Request = Response = JSONResponse = None

"""Imported at module level, and that is not a style preference.

This module carries ``from __future__ import annotations``, so every annotation
is a string that FastAPI resolves later against *module* globals. Imported
inside :func:`install`, ``Request`` would not be there when it looked -- and
FastAPI's answer to an annotation it cannot resolve is not an error, it is to
treat the parameter as a request body. Every route then answers 422 to a
perfectly good call, which is a failure mode that looks like a client bug.

Guarded because this file is imported when the extension is imported, and an
environment without FastAPI should reach :func:`install` and answer False rather
than take the WebUI down on the way past.
"""

logger = logging.getLogger("model_chain")
"""Handler is attached once, in mc_memory."""

PREFIX = "/model-chain/voice"

STATUS_ROUTE = f"{PREFIX}/status"
STT_ROUTE = f"{PREFIX}/stt"
TTS_ROUTE = f"{PREFIX}/tts"
INSTALL_ROUTE = f"{PREFIX}/install"

ROUTES = (STATUS_ROUTE, STT_ROUTE, TTS_ROUTE, INSTALL_ROUTE)

TOKEN_HEADER = "x-model-chain-voice"

MAX_AUDIO_BYTES = 4 * 1024 * 1024
"""Sixty seconds of 16 kHz mono PCM16 is about 1.9 MB, so this is generous and
is still a refusal that happens before a single byte reaches an inference
engine."""

MAX_SECONDS = 60.0
ACCEPTED_RATES = (16000,)
TARGET_TTL = 120.0

_lock = threading.Lock()
_targets: dict[str, dict] = {}
_token = secrets.token_urlsafe(24)
"""This process's page token. Regenerated by a restart, which is what makes a
tab left open across one fail with "reload the page" rather than half-work."""


def session_token() -> str:
    return _token


# --------------------------------------------------------------------------- #
# Speech targets
# --------------------------------------------------------------------------- #


def remember_reply(text: str) -> str:
    """Take an immutable snapshot of a completed reply. Returns its token.

    The snapshot is the design decision (R2-5, I-13). A message index would have
    been smaller and is wrong: the thread can be edited, regenerated, branched
    or switched between the run finishing and the browser asking for audio, and
    every one of those changes what an index means. A copy of the string cannot
    change.
    """
    snapshot = str(text or "")
    if not snapshot.strip():
        return ""
    token = secrets.token_urlsafe(18)
    now = time.monotonic()
    with _lock:
        _expire(now)
        _targets[token] = {"text": snapshot, "created": now, "session": _token}
    return token


def take_reply(token: str) -> str:
    """Consume one target, atomically. Empty string if there is not one.

    One-shot because a token that could be replayed is a token a page left open
    could make speak the same reply again on every refresh, and because the
    whole life of a target is one POST from one page.
    """
    key = str(token or "")
    now = time.monotonic()
    with _lock:
        _expire(now)
        found = _targets.pop(key, None)
    if found is None or found.get("session") != _token:
        return ""
    return found["text"]


def _expire(now: float) -> None:
    for key in [key for key, item in _targets.items() if now - item["created"] > TARGET_TTL]:
        _targets.pop(key, None)


def forget_targets() -> None:
    """Drop every pending target. Used by shutdown and by the tests."""
    with _lock:
        _targets.clear()


# --------------------------------------------------------------------------- #
# Validation
# --------------------------------------------------------------------------- #


class Refused(Exception):
    """A request that is not going to reach an inference engine."""

    def __init__(self, status: int, reason: str):
        super().__init__(reason)
        self.status = status
        self.reason = reason


def validate_wav(data: bytes) -> dict:
    """Parse enough of a RIFF/WAVE header to refuse everything unwanted.

    Written out rather than handed to ``wave`` because this is the boundary: the
    module that raises on a malformed chunk table should be the one in front of
    the worker, not the worker. What is accepted is deliberately narrow -- the
    browser is ours and produces exactly one shape -- and everything else is a
    sentence rather than an exception two processes away.
    """
    if not data:
        raise Refused(400, "No audio was received.")
    if len(data) > MAX_AUDIO_BYTES:
        raise Refused(413, "That recording is too large.")
    if len(data) < 44 or data[:4] != b"RIFF" or data[8:12] != b"WAVE":
        raise Refused(400, "That upload is not a WAV recording.")

    offset, found = 12, {}
    while offset + 8 <= len(data):
        name = data[offset:offset + 4]
        (size,) = struct.unpack_from("<I", data, offset + 4)
        body = offset + 8
        if body + size > len(data):
            # A chunk claiming more than the file holds is the malformed length
            # table the design intent asks to be refused by name.
            raise Refused(400, "That recording's header is malformed.")
        if name == b"fmt " and size >= 16:
            audio_format, channels, rate, _bps, _align, bits = struct.unpack_from(
                "<HHIIHH", data, body)
            found["fmt"] = (audio_format, channels, rate, bits)
        elif name == b"data":
            found["data"] = size
        offset = body + size + (size % 2)

    if "fmt" not in found or "data" not in found:
        raise Refused(400, "That recording is not a complete WAV.")
    audio_format, channels, rate, bits = found["fmt"]
    if audio_format != 1:
        raise Refused(400, "Voice Chat accepts uncompressed PCM audio only.")
    if channels != 1:
        raise Refused(400, "Voice Chat accepts mono audio only.")
    if bits != 16:
        raise Refused(400, "Voice Chat accepts 16-bit audio only.")
    if rate not in ACCEPTED_RATES:
        raise Refused(400, "Voice Chat accepts 16 kHz audio only.")
    frames = found["data"] // 2
    seconds = frames / float(rate)
    if frames <= 0:
        raise Refused(400, "That recording is empty.")
    if seconds > MAX_SECONDS + 0.5:
        raise Refused(400, "That recording is longer than Voice Chat accepts.")
    if seconds < 0.2:
        raise Refused(400, "Hold to speak.")
    return {"seconds": seconds, "rate": rate, "frames": frames}


# --------------------------------------------------------------------------- #
# Who is asking
# --------------------------------------------------------------------------- #


def _authorised(request) -> bool:
    """Whether this caller is one the WebUI itself would have served.

    No auth configured -> everybody, exactly as the rest of the WebUI. Auth
    configured -> a Gradio session cookie this app issued, looked up in the
    app's own token table. Deliberately Gradio's table and not a second one:
    a Voice Chat that maintained its own idea of who is logged in would be a
    second login system, and the design intent says in as many words that the
    page token is not that.
    """
    app = getattr(request, "app", None)
    tokens = getattr(app, "tokens", None)
    auth = getattr(app, "auth", None)
    if auth is None:
        auth = _command_line_auth()
    if not auth:
        return True
    if not isinstance(tokens, dict):
        # Auth is on and this build does not expose the table to check against.
        # Refusing is the only safe answer: an extension route that cannot prove
        # who is calling must not be the way in to a protected WebUI.
        logger.warning("Model Chain: Voice Chat cannot verify the WebUI's own login on this "
                       "build, so its routes are refusing every caller")
        return False
    cookies = getattr(request, "cookies", None) or {}
    for name in ("access-token", "access-token-unsecure"):
        value = cookies.get(name)
        if value and value in tokens:
            return True
    return False


def _command_line_auth():
    try:
        from modules import shared

        return getattr(shared.cmd_opts, "gradio_auth", None) or getattr(
            shared.cmd_opts, "gradio_auth_path", None)
    except Exception:
        return None


def _same_origin(request) -> bool:
    """Reject a page on another origin driving these routes with our cookies.

    Only when an ``Origin`` is present: a same-origin ``fetch`` from some
    browsers does not send one, and treating its absence as hostile would break
    the ordinary case to defend against a case the token already covers.
    ``X-Forwarded-Host`` is honoured because a reverse proxy is a documented
    deployment -- and it is compared rather than trusted blindly, which is the
    difference between supporting a proxy and having no check at all.
    """
    headers = getattr(request, "headers", {}) or {}
    origin = headers.get("origin")
    if not origin:
        return True
    wanted = {headers.get("host"), headers.get("x-forwarded-host")}
    wanted.discard(None)
    try:
        from urllib.parse import urlsplit

        netloc = urlsplit(origin).netloc
    except Exception:
        return False
    return bool(netloc) and netloc in wanted


def _matches_token(offered: str) -> bool:
    """Constant-time comparison that cannot be made to raise.

    ``compare_digest`` on ``str`` requires both sides to be ASCII and raises
    ``TypeError`` otherwise -- so a header with one accented character would
    leave this function through the route's generic handler as a 500 rather
    than as the 403 it is. Encoded first, which makes every input comparable.
    """
    try:
        return secrets.compare_digest(str(offered or "").encode("utf-8"),
                                      _token.encode("utf-8"))
    except Exception:
        return False


def _checked(request, route: str = "") -> None:
    """Every gate one voice route passes, in the order they cost.

    Each refusal names *which* gate closed, in the log. Without that a 403 is
    indistinguishable from a 401 from a route that is not there, and the only
    way to tell them apart is to open the browser's developer tools -- which is
    the answer this repository has already decided is not an answer (see
    :mod:`mc_literal_report`). One line per refusal, no content in it, and the
    reason is one of three words chosen here.
    """
    headers = getattr(request, "headers", {}) or {}
    offered = headers.get(TOKEN_HEADER)
    if not _matches_token(offered):
        _refused(route, "no page token was sent" if not offered
                 else "the page token did not match this WebUI process")
        raise Refused(403, "This page is out of date with the WebUI. Reload it.")
    if not _same_origin(request):
        _refused(route, "the Origin header did not match this WebUI's host")
        raise Refused(403, "That request did not come from this WebUI.")
    if not _authorised(request):
        _refused(route, "the caller is not signed in to the WebUI")
        raise Refused(401, "Sign in to the WebUI to use Voice Chat.")


def _refused(route: str, reason: str) -> None:
    logger.warning("Model Chain: Voice Chat refused a request to %s — %s",
                   route or "a voice route", reason)


# --------------------------------------------------------------------------- #
# The payloads, built without a framework
# --------------------------------------------------------------------------- #


def status_payload() -> dict:
    """What the browser needs to draw the microphone, and nothing else.

    No paths, no pids, no model filenames: this is read by a page and everything
    in it is a fact that page needs. The messages are the same sentences
    Settings shows, so a user reading one and a user reading the other are being
    told the same thing.
    """
    found = models.status()
    return {
        "ok": True,
        "ready": found.ready,
        "runtime_ready": found.runtime_ready,
        "stt_ready": found.stt_ready,
        "tts_ready": found.tts_ready,
        "platform_supported": found.platform_supported,
        "runtime_message": found.runtime_message,
        "stt_message": found.stt_message,
        "tts_message": found.tts_message,
        "auto_send": state.auto_send(),
        "auto_speak": state.auto_speak(),
        "busy": found.busy,
        "progress": models.progress(),
        "not_ready_message": ("Voice Chat is not set up. Install both models in "
                              "Settings → Voice Chat."),
    }


def transcribe(body: bytes) -> dict:
    """The STT route's body: validate, transcribe, and let the bytes go."""
    shape = validate_wav(body)
    try:
        found = runtime.transcribe(body)
    except runtime.VoiceRuntimeError as exc:
        raise Refused(503, str(exc)) from None
    text = found.get("text") or ""
    logger.info("Model Chain: Voice STT finished — %.1f s audio in %.1f s",
                shape["seconds"], float(found.get("elapsed") or 0.0))
    if not text.strip():
        return {"ok": False, "error": "No speech was detected.", "text": ""}
    return {"ok": True, "text": text, "auto_send": state.auto_send(),
            "request_id": secrets.token_hex(6)}


def speak(token: str) -> bytes:
    """The TTS route's body: consume one target and synthesize its snapshot.

    A failure after consumption is reported, never repaired. Re-resolving "the
    current last reply" to try again would quietly speak a different message
    than the one the token stood for, which is the whole class of bug R2-5
    exists to prevent.
    """
    text = take_reply(token)
    if not text:
        raise Refused(404, "There is nothing waiting to be read aloud.")
    try:
        audio = runtime.synthesize(text)
    except runtime.VoiceRuntimeError as exc:
        raise Refused(503, str(exc)) from None
    logger.info("Model Chain: Voice TTS finished — %d characters, %d bytes of audio",
                len(text), len(audio))
    return audio


def provision(kind: str) -> dict:
    """Start installing one bundle in the background, and say so immediately.

    In the background because a download is minutes and an HTTP request that
    takes minutes is a request a phone's browser will give up on. The row polls
    :func:`status_payload` for the rest, which is also what makes the Settings
    page and the Voice flyout agree without either of them owning the download.

    Everything that can be decided *before* the thread starts is decided here
    and answered in the response. That is the correction to the first version,
    which started a thread unconditionally and let it discover on the other side
    that this build cannot install anything -- so the browser was told "started"
    and the row sat on "Starting…" for as long as somebody was willing to watch
    it. A refusal a caller is waiting for belongs in the reply to that caller.
    """
    if kind not in ("stt", "tts"):
        raise Refused(400, "Voice Chat installs a speech-to-text or a text-to-speech model.")

    already = models.progress().get(kind) or {}
    if already.get("running"):
        logger.info("Model Chain: Voice Chat was asked to install the %s model again while "
                    "it is already installing", kind.upper())
        return {"ok": True, "already": True}

    refusal = models.refusal(kind)
    if refusal:
        logger.warning("Model Chain: Voice Chat refused to install the %s model — %s",
                       kind.upper(), refusal)
        raise Refused(409, refusal)

    logger.info("Model Chain: Voice Chat install requested for the %s model", kind.upper())

    def run():
        try:
            models.install(kind)
        except Exception:
            # Already logged with its reason, and already recorded where the
            # Settings row will draw it -- see mc_voice_models._claim.
            logger.debug("Model Chain: the Voice Chat install thread ended on an error",
                         exc_info=True)

    threading.Thread(target=run, name=f"mc-voice-install-{kind}", daemon=True).start()
    return {"ok": True, "already": False}


# --------------------------------------------------------------------------- #
# Registration
# --------------------------------------------------------------------------- #


_installed = False


def install(_demo=None, app=None) -> bool:
    """Register the routes on the WebUI's FastAPI app. Idempotent, never fatal.

    Signature is ``script_callbacks.on_app_started``'s. A UI reload calls it
    again and a second registration would give FastAPI two matching routes for
    one path, so the existing paths are looked for first -- ``mc_literal_report``
    established the pattern and this follows it.
    """
    global _installed

    if app is None or not hasattr(app, "add_api_route"):
        return False
    existing = {getattr(route, "path", None) for route in getattr(app, "routes", [])}
    if all(path in existing for path in ROUTES):
        _installed = True
        return True

    if Request is None:
        logger.debug("Model Chain: Voice Chat has no FastAPI to register routes on")
        return False

    def _refusal(exc):
        return JSONResponse({"ok": False, "error": exc.reason}, status_code=exc.status)

    async def voice_status(request: Request):
        try:
            _checked(request, STATUS_ROUTE)
        except Refused as exc:
            return _refusal(exc)
        return JSONResponse(status_payload())

    async def voice_stt(request: Request):
        try:
            _checked(request, STT_ROUTE)
            body = await request.body()
            return JSONResponse(transcribe(body))
        except Refused as exc:
            return _refusal(exc)
        except Exception:
            logger.warning("Model Chain: a Voice Chat transcription failed", exc_info=True)
            return JSONResponse(
                {"ok": False, "error": "Voice transcription failed. Your message was not sent."},
                status_code=500)

    async def voice_tts(request: Request):
        try:
            _checked(request, TTS_ROUTE)
            payload = await request.json()
            audio = speak(str((payload or {}).get("token") or ""))
        except Refused as exc:
            return _refusal(exc)
        except Exception:
            logger.warning("Model Chain: a Voice Chat synthesis failed", exc_info=True)
            return JSONResponse(
                {"ok": False,
                 "error": "The reply was generated, but Voice could not read it aloud."},
                status_code=500)
        return Response(content=audio, media_type="audio/wav", headers={
            # Never cached, anywhere: a spoken reply is content, and a proxy or
            # a browser holding a copy of it is a copy nobody asked for.
            "Cache-Control": "no-store, max-age=0",
            "Pragma": "no-cache",
            "Content-Disposition": "inline",
        })

    async def voice_install(request: Request):
        try:
            _checked(request, INSTALL_ROUTE)
            payload = await request.json()
            return JSONResponse(provision(str((payload or {}).get("kind") or "")))
        except Refused as exc:
            return _refusal(exc)
        except Exception:
            logger.warning("Model Chain: a Voice Chat install request failed", exc_info=True)
            return JSONResponse({"ok": False, "error": "Voice Chat could not start that "
                                                       "download."}, status_code=500)

    try:
        for path, handler in ((STATUS_ROUTE, voice_status), (STT_ROUTE, voice_stt),
                              (TTS_ROUTE, voice_tts), (INSTALL_ROUTE, voice_install)):
            if path not in existing:
                app.add_api_route(path, handler, methods=["POST"])
    except Exception:
        logger.debug("Model Chain: could not register the Voice Chat routes", exc_info=True)
        return False
    _installed = True
    found = models.status()
    logger.info("Model Chain: Voice Chat routes registered at %s", ", ".join(ROUTES))
    logger.info("Model Chain: Voice Chat data directory is %s", paths.data_root())
    logger.info("Model Chain: Voice Chat status — runtime %s, speech-to-text %s, "
                "text-to-speech %s", found.runtime_message, found.stt_message,
                found.tts_message)
    return True
